/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sourceforge.jbarcodebean.JBarcodeBean;
import net.sourceforge.jbarcodebean.model.Code128;

/**
 *
 * @author qr_monitor
 */
public class Barcode extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps,ps1;
ResultSet rs;


    /**
     * Creates new form Barcode
     */
    public Barcode() {
        initComponents();
    }public Barcode(String msg){
        initComponents();
        lblRole.setText(msg);
        load_stud_info();
        
        
    }
     public void load_stud_info(){
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("SELECT * FROM student_info");
        rs=ps.executeQuery();
        
         while (rs.next()){
             
             String studid = rs.getString("studentID");
             String name = rs.getString("name");
             String course = rs.getString("course");
             String year = rs.getString("year_level");
          
            
             
             String tbData[] = {studid,name,course,year};
             DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
             
             tbl.addRow(tbData);
         
        
             
         } 
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        
    }
         
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnStudReg = new javax.swing.JButton();
        btnAccReg = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStud = new javax.swing.JTable();
        pnlB3 = new javax.swing.JPanel();
        pnlB2 = new javax.swing.JPanel();
        pnlB9 = new javax.swing.JPanel();
        pnlB4 = new javax.swing.JPanel();
        pnlB7 = new javax.swing.JPanel();
        pnlB10 = new javax.swing.JPanel();
        pnlB5 = new javax.swing.JPanel();
        pnlB6 = new javax.swing.JPanel();
        pnlB1 = new javax.swing.JPanel();
        pnlB8 = new javax.swing.JPanel();
        pnlB12 = new javax.swing.JPanel();
        pnlB11 = new javax.swing.JPanel();
        btnGenerate = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbB1 = new javax.swing.JRadioButton();
        txtB1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbB2 = new javax.swing.JRadioButton();
        txtB2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbB3 = new javax.swing.JRadioButton();
        txtB3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbB4 = new javax.swing.JRadioButton();
        txtB4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbB5 = new javax.swing.JRadioButton();
        txtB5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbB6 = new javax.swing.JRadioButton();
        txtB6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbB7 = new javax.swing.JRadioButton();
        txtB7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbB10 = new javax.swing.JRadioButton();
        txtB10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbB11 = new javax.swing.JRadioButton();
        txtB11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbB8 = new javax.swing.JRadioButton();
        txtB8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbB9 = new javax.swing.JRadioButton();
        txtB9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbB12 = new javax.swing.JRadioButton();
        txtB12 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 760));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudReg.setBackground(new java.awt.Color(204, 255, 204));
        btnStudReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnStudReg.setText("Student Register");
        btnStudReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        btnAccReg.setBackground(new java.awt.Color(204, 255, 204));
        btnAccReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAccReg.setText("Account Register");
        btnAccReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        btnLogs.setBackground(new java.awt.Color(204, 255, 204));
        btnLogs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogs.setText("Logs");
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, -1));

        jButton2.setBackground(new java.awt.Color(51, 255, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Create Barcode");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, 30));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 50, 20));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 200, 24));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Search:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        tblStud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Course", "Year Level"
            }
        ));
        tblStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStud);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 390, 400));

        pnlB3.setBackground(new java.awt.Color(255, 255, 255));
        pnlB3.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 300, 100));

        pnlB2.setBackground(new java.awt.Color(255, 255, 255));
        pnlB2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 300, 100));

        pnlB9.setBackground(new java.awt.Color(255, 255, 255));
        pnlB9.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, 300, 100));

        pnlB4.setBackground(new java.awt.Color(255, 255, 255));
        pnlB4.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 300, 100));

        pnlB7.setBackground(new java.awt.Color(255, 255, 255));
        pnlB7.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 300, 100));

        pnlB10.setBackground(new java.awt.Color(255, 255, 255));
        pnlB10.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 300, 100));

        pnlB5.setBackground(new java.awt.Color(255, 255, 255));
        pnlB5.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 300, 100));

        pnlB6.setBackground(new java.awt.Color(255, 255, 255));
        pnlB6.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, 300, 100));

        pnlB1.setBackground(new java.awt.Color(255, 255, 255));
        pnlB1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 300, 100));

        pnlB8.setBackground(new java.awt.Color(255, 255, 255));
        pnlB8.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 300, 100));

        pnlB12.setBackground(new java.awt.Color(255, 255, 255));
        pnlB12.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 300, 100));

        pnlB11.setBackground(new java.awt.Color(255, 255, 255));
        pnlB11.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 300, 100));

        btnGenerate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, -1));

        btnExport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jPanel1.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        buttonGroup1.add(cmbB1);
        cmbB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB1MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 20, 30));
        jPanel1.add(txtB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 260, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        buttonGroup1.add(cmbB2);
        cmbB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB2MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 20, 30));
        jPanel1.add(txtB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 260, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Student ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, -1));

        buttonGroup1.add(cmbB3);
        cmbB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB3MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 20, 30));
        jPanel1.add(txtB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, 260, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        buttonGroup1.add(cmbB4);
        cmbB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB4MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 20, 30));
        jPanel1.add(txtB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 260, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Student ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        buttonGroup1.add(cmbB5);
        cmbB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB5MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 20, 30));
        jPanel1.add(txtB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 260, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Student ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, -1));

        buttonGroup1.add(cmbB6);
        cmbB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB6MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, 20, 30));
        jPanel1.add(txtB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 260, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Student ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        buttonGroup1.add(cmbB7);
        cmbB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB7MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 20, 30));
        jPanel1.add(txtB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 260, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Student ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, -1));

        buttonGroup1.add(cmbB10);
        cmbB10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB10MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 20, 30));
        jPanel1.add(txtB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 260, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Student ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, -1, -1));

        buttonGroup1.add(cmbB11);
        cmbB11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB11MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 20, 30));
        jPanel1.add(txtB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 260, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Student ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, -1, -1));

        buttonGroup1.add(cmbB8);
        cmbB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB8MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 20, 30));
        jPanel1.add(txtB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 260, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Student ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, -1, -1));

        buttonGroup1.add(cmbB9);
        cmbB9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB9MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, 20, 30));
        jPanel1.add(txtB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 500, 260, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Student ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 650, -1, -1));

        buttonGroup1.add(cmbB12);
        cmbB12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbB12MouseClicked(evt);
            }
        });
        jPanel1.add(cmbB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 670, 20, 30));
        jPanel1.add(txtB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 670, 260, 30));

        btnClear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudRegActionPerformed
        String msg=lblRole.getText();

        new StudentRegister(msg).setVisible(true);
        setVisible(false);

        /*StudentRegister sr = new StudentRegister();
        sr.show();
        dispose();*/
    }//GEN-LAST:event_btnStudRegActionPerformed

    private void btnAccRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccRegActionPerformed
        if(lblRole.getText().equals("Professor")){
            JOptionPane.showMessageDialog(this, "Access Denied!");

        }else {
            String msg=lblRole.getText();
            new AccRegister(msg).setVisible(true);
            setVisible(false);
        }

    }//GEN-LAST:event_btnAccRegActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        String msg=lblRole.getText();

        new logs(msg).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        /*Homepage hp = new Homepage();
        hp.show();
        dispose();*/
        String msg=lblRole.getText();

        new Homepage(msg).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:

        DefaultTableModel tb = (DefaultTableModel) tblStud.getModel();
        TableRowSorter<DefaultTableModel> tbl = new TableRowSorter<>(tb);
        tblStud.setRowSorter(tbl);
        tbl.setRowFilter(RowFilter.regexFilter(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblStud.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        if(cmbB1.getSelectedObjects()!=null)
        {
        txtB1.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB2.getSelectedObjects()!=null)
        {
        txtB2.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB3.getSelectedObjects()!=null)
        {
        txtB3.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB4.getSelectedObjects()!=null)
        {
        txtB4.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB5.getSelectedObjects()!=null)
        {
        txtB5.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB6.getSelectedObjects()!=null)
        {
        txtB6.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB7.getSelectedObjects()!=null)
        {
        txtB7.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB8.getSelectedObjects()!=null)
        {
        txtB8.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB9.getSelectedObjects()!=null)
        {
        txtB9.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB10.getSelectedObjects()!=null)
        {
        txtB10.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB11.getSelectedObjects()!=null)
        {
        txtB11.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else if(cmbB12.getSelectedObjects()!=null)
        {
        txtB12.setText(tbl.getValueAt(selectedRow, 0).toString());
        }else
        {
            
        }
        
    }//GEN-LAST:event_tblStudMouseClicked

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String b1 = txtB1.getText().trim();
        String b2 = txtB2.getText().trim();
        String b3 = txtB3.getText().trim();
        String b4 = txtB4.getText().trim();
        String b5 = txtB5.getText().trim();
        String b6 = txtB6.getText().trim();
        String b7 = txtB7.getText().trim();
        String b8 = txtB8.getText().trim();
        String b9 = txtB9.getText().trim();
        String b10 = txtB10.getText().trim();
        String b11 = txtB11.getText().trim();
        String b12 = txtB12.getText().trim();
        
        if (!b1.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b1);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB1.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB1.add(lblBarcode);
            pnlB1.revalidate();
            pnlB1.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b2.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b2);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB2.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB2.add(lblBarcode);
            pnlB2.revalidate();
            pnlB2.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b3.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b3);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB3.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB3.add(lblBarcode);
            pnlB3.revalidate();
            pnlB3.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b4.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b4);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB4.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB4.add(lblBarcode);
            pnlB4.revalidate();
            pnlB4.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b5.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b5);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB5.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB5.add(lblBarcode);
            pnlB5.revalidate();
            pnlB5.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b6.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b6);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB6.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB6.add(lblBarcode);
            pnlB6.revalidate();
            pnlB6.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b7.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b7);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB7.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB7.add(lblBarcode);
            pnlB7.revalidate();
            pnlB7.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b8.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b8);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB8.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB8.add(lblBarcode);
            pnlB8.revalidate();
            pnlB8.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b9.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b9);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB9.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB9.add(lblBarcode);
            pnlB9.revalidate();
            pnlB9.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b10.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b10);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB10.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB10.add(lblBarcode);
            pnlB10.revalidate();
            pnlB10.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b11.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b11);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB11.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB11.add(lblBarcode);
            pnlB11.revalidate();
            pnlB11.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if (!b12.isEmpty()) 
        {
            try {
            JBarcodeBean barcodeBean = new JBarcodeBean();
            barcodeBean.setCodeType(new Code128());
            barcodeBean.setCode(b12);

            int barcodeWidth = 300;
            int barcodeHeight = 100;
            BufferedImage image = barcodeBean.draw(new BufferedImage(barcodeWidth, barcodeHeight, BufferedImage.TYPE_INT_BGR));

            ImageIcon iconBarcode = new ImageIcon(image);
            pnlB12.removeAll(); 
            JLabel lblBarcode = new JLabel(iconBarcode);
            pnlB12.add(lblBarcode);
            pnlB12.revalidate();
            pnlB12.repaint();

        } catch (Exception ex) {
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else
        {
        
        }

       
        
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tblStud.clearSelection();
        txtB1.setText("");
        txtB2.setText("");
        txtB3.setText("");
        txtB4.setText("");
        txtB5.setText("");
        txtB6.setText("");
        txtB7.setText("");
        txtB8.setText("");
        txtB9.setText("");
        txtB10.setText("");
        txtB11.setText("");
        txtB12.setText("");
        
        pnlB1.removeAll();
        pnlB1.revalidate();
        pnlB1.repaint();
        
        pnlB2.removeAll();
        pnlB2.revalidate();
        pnlB2.repaint();
        
        pnlB3.removeAll();
        pnlB3.revalidate();
        pnlB3.repaint();
        
        pnlB4.removeAll();
        pnlB4.revalidate();
        pnlB4.repaint();
        
        pnlB5.removeAll();
        pnlB5.revalidate();
        pnlB5.repaint();
        
        pnlB6.removeAll();
        pnlB6.revalidate();
        pnlB6.repaint();
        
        pnlB7.removeAll();
        pnlB7.revalidate();
        pnlB7.repaint();
        
        pnlB8.removeAll();
        pnlB8.revalidate();
        pnlB8.repaint();
        
        pnlB9.removeAll();
        pnlB9.revalidate();
        pnlB9.repaint();
        
        pnlB10.removeAll();
        pnlB10.revalidate();
        pnlB10.repaint();
        
        pnlB11.removeAll();
        pnlB11.revalidate();
        pnlB11.repaint();
        
        pnlB12.removeAll();
        pnlB12.revalidate();
        pnlB12.repaint();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        printPanels(pnlB1, pnlB2, pnlB3, pnlB4, pnlB5, pnlB6, pnlB7, pnlB8, pnlB9, pnlB10, pnlB11, pnlB12);
      
    }//GEN-LAST:event_btnExportActionPerformed

    private void cmbB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB1MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB1MouseClicked

    private void cmbB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB2MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB2MouseClicked

    private void cmbB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB3MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB3MouseClicked

    private void cmbB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB4MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB4MouseClicked

    private void cmbB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB5MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB5MouseClicked

    private void cmbB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB6MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB6MouseClicked

    private void cmbB7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB7MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB7MouseClicked

    private void cmbB8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB8MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB8MouseClicked

    private void cmbB9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB9MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB9MouseClicked

    private void cmbB10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB10MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB10MouseClicked

    private void cmbB11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB11MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB11MouseClicked

    private void cmbB12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbB12MouseClicked
        // TODO add your handling code here:
        tblStud.clearSelection();
    }//GEN-LAST:event_cmbB12MouseClicked

    private static void printPanels(JPanel pnlB1, JPanel pnlB2,JPanel pnlB3,JPanel pnlB4,JPanel pnlB5,JPanel pnlB6,JPanel pnlB7,JPanel pnlB8,JPanel pnlB9,JPanel pnlB10,JPanel pnlB11,JPanel pnlB12) {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics g, PageFormat pageFormat, int pageIndex) {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                try {
                    // Print pnlB1
                    BufferedImage biB1 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB1 = biB1.createGraphics();
                    pnlB1.paint(g2dB1);
                    g2dB1.dispose();
                    g2d.drawImage(biB1, 25, 0, null);

                    // Print pnlB2
                    BufferedImage biB2 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB2 = biB2.createGraphics();
                    pnlB2.paint(g2dB2);
                    g2dB2.dispose();
                    g2d.drawImage(biB2, 300, 0, null);
                    
                    BufferedImage biB3 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB3 = biB3.createGraphics();
                    pnlB3.paint(g2dB3);
                    g2dB3.dispose();
                    g2d.drawImage(biB3, 25, 150, null);

                    // Print pnlB2
                    BufferedImage biB4 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB4 = biB4.createGraphics();
                    pnlB4.paint(g2dB4);
                    g2dB4.dispose();
                    g2d.drawImage(biB4, 300, 150, null);
                    
                    BufferedImage biB5 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB5 = biB5.createGraphics();
                    pnlB5.paint(g2dB5);
                    g2dB5.dispose();
                    g2d.drawImage(biB5, 25, 300, null);

                    // Print pnlB2
                    BufferedImage biB6 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB6 = biB6.createGraphics();
                    pnlB6.paint(g2dB6);
                    g2dB6.dispose();
                    g2d.drawImage(biB6, 300, 300, null);
                    
                    BufferedImage biB7 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB7 = biB7.createGraphics();
                    pnlB7.paint(g2dB7);
                    g2dB7.dispose();
                    g2d.drawImage(biB7, 25, 450, null);

                    // Print pnlB2
                    BufferedImage biB8 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB8 = biB8.createGraphics();
                    pnlB8.paint(g2dB8);
                    g2dB8.dispose();
                    g2d.drawImage(biB8, 300, 450, null);
                    
                    BufferedImage biB9 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB9 = biB9.createGraphics();
                    pnlB9.paint(g2dB9);
                    g2dB9.dispose();
                    g2d.drawImage(biB9, 25, 600, null);

                    // Print pnlB2
                    BufferedImage biB10 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB10 = biB10.createGraphics();
                    pnlB10.paint(g2dB10);
                    g2dB10.dispose();
                    g2d.drawImage(biB10, 300, 600, null);
                    
                    BufferedImage biB11 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB11 = biB11.createGraphics();
                    pnlB11.paint(g2dB11);
                    g2dB11.dispose();
                    g2d.drawImage(biB11, 25, 750, null);

                    // Print pnlB2
                    BufferedImage biB12 = new BufferedImage(300, 100, BufferedImage.TYPE_INT_BGR);
                    Graphics2D g2dB12 = biB12.createGraphics();
                    pnlB12.paint(g2dB12);
                    g2dB12.dispose();
                    g2d.drawImage(biB12, 300, 750, null);

                } catch (Exception e) {
                    e.printStackTrace();
                }

                return PAGE_EXISTS;
            }
        });

        try {
            if (job.printDialog()) {
                job.print();
            }
        } catch (PrinterException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccReg;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudReg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cmbB1;
    private javax.swing.JRadioButton cmbB10;
    private javax.swing.JRadioButton cmbB11;
    private javax.swing.JRadioButton cmbB12;
    private javax.swing.JRadioButton cmbB2;
    private javax.swing.JRadioButton cmbB3;
    private javax.swing.JRadioButton cmbB4;
    private javax.swing.JRadioButton cmbB5;
    private javax.swing.JRadioButton cmbB6;
    private javax.swing.JRadioButton cmbB7;
    private javax.swing.JRadioButton cmbB8;
    private javax.swing.JRadioButton cmbB9;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel pnlB1;
    private javax.swing.JPanel pnlB10;
    private javax.swing.JPanel pnlB11;
    private javax.swing.JPanel pnlB12;
    private javax.swing.JPanel pnlB2;
    private javax.swing.JPanel pnlB3;
    private javax.swing.JPanel pnlB4;
    private javax.swing.JPanel pnlB5;
    private javax.swing.JPanel pnlB6;
    private javax.swing.JPanel pnlB7;
    private javax.swing.JPanel pnlB8;
    private javax.swing.JPanel pnlB9;
    private javax.swing.JTable tblStud;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB10;
    private javax.swing.JTextField txtB11;
    private javax.swing.JTextField txtB12;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtB3;
    private javax.swing.JTextField txtB4;
    private javax.swing.JTextField txtB5;
    private javax.swing.JTextField txtB6;
    private javax.swing.JTextField txtB7;
    private javax.swing.JTextField txtB8;
    private javax.swing.JTextField txtB9;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
