/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author qr_monitor
 */
public class logs extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form logs
     */
    public logs() {
        initComponents();
       
    }public logs(String msg){
        initComponents();
        lblRole.setText(msg);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStudReg = new javax.swing.JButton();
        btnAccReg = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLog = new javax.swing.JTextField();
        txtAcc = new javax.swing.JTextField();
        txtSeatId = new javax.swing.JTextField();
        txtSid = new javax.swing.JTextField();
        txtStud = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtIn = new javax.swing.JTextField();
        txtOut = new javax.swing.JTextField();
        txtSeat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 760));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudReg.setBackground(new java.awt.Color(204, 255, 204));
        btnStudReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnStudReg.setText("Student Register");
        btnStudReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        btnAccReg.setBackground(new java.awt.Color(204, 255, 204));
        btnAccReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAccReg.setText("Account Register");
        btnAccReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        btnLogs.setBackground(new java.awt.Color(51, 255, 102));
        btnLogs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogs.setText("Logs");
        jPanel1.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 70, 20));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Log ID", "Account ID", "Seat Plan ID", "SID", "Student ID", "Date", "Time In", "Time Out", "Seat"
            }
        ));
        tblLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLog);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 1260, 420));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Log ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Account ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Seat Plan ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("SID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Student ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Time in:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Time out:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Seat:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, -1, -1));

        txtLog.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLog.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLog.setEnabled(false);
        jPanel1.add(txtLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 200, 24));

        txtAcc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAcc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAcc.setEnabled(false);
        jPanel1.add(txtAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 24));

        txtSeatId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSeatId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSeatId.setEnabled(false);
        jPanel1.add(txtSeatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 200, 24));

        txtSid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSid.setEnabled(false);
        jPanel1.add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 200, 24));

        txtStud.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtStud.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStud.setEnabled(false);
        jPanel1.add(txtStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 200, 24));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDate.setEnabled(false);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 200, 24));

        txtIn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtIn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIn.setEnabled(false);
        jPanel1.add(txtIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 200, 24));

        txtOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtOut.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtOut.setEnabled(false);
        jPanel1.add(txtOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 200, 24));

        txtSeat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSeat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSeat.setEnabled(false);
        jPanel1.add(txtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 200, 24));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Search");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 200, 24));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Create Barcode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudRegActionPerformed
        // TODO add your handling code here:
        /*StudentRegister sr = new StudentRegister();
        sr.show();
        dispose();*/
        String msg=lblRole.getText();

        new StudentRegister(msg).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnStudRegActionPerformed

    private void btnAccRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccRegActionPerformed
        // TODO add your handling code here:
        if(lblRole.getText().equals("Professor")){
            JOptionPane.showMessageDialog(this, "Access Denied!");

        }else{
            String msg=lblRole.getText();
            new AccRegister(msg).setVisible(true);
            setVisible(false);
        }

    }//GEN-LAST:event_btnAccRegActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        /*Homepage hp = new Homepage();
        hp.show();
        dispose();*/
        String msg=lblRole.getText();

        new Homepage(msg).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogMouseClicked
        // TODO add your handling code here:
        
        
        /*int selectedRow = tblLog.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblLog.getModel();
        txtLog.setText(tbl.getValueAt(selectedRow, 0).toString());
        txtAcc.setText(tbl.getValueAt(selectedRow, 1).toString());
        txtSeatId.setText(tbl.getValueAt(selectedRow, 2).toString());
        txtSid.setText(tbl.getValueAt(selectedRow, 3).toString());
        txtStud.setText(tbl.getValueAt(selectedRow, 4).toString());
        txtDate.setText(tbl.getValueAt(selectedRow, 5).toString());
        txtIn.setText(tbl.getValueAt(selectedRow, 6).toString());
        txtOut.setText(tbl.getValueAt(selectedRow, 7).toString());
        txtSeat.setText(tbl.getValueAt(selectedRow, 8).toString());*/
        int selectedRow = tblLog.getSelectedRow();
if (selectedRow >= 0) {  // Check if a row is selected
    DefaultTableModel tbl = (DefaultTableModel) tblLog.getModel();
    try {
        // Retrieve values and handle potential nulls
        txtLog.setText(getValueOrEmpty(tbl, selectedRow, 0));
        txtAcc.setText(getValueOrEmpty(tbl, selectedRow, 1));
        txtSeatId.setText(getValueOrEmpty(tbl, selectedRow, 2));
        txtSid.setText(getValueOrEmpty(tbl, selectedRow, 3));
        txtStud.setText(getValueOrEmpty(tbl, selectedRow, 4));
        txtDate.setText(getValueOrEmpty(tbl, selectedRow, 5));
        txtIn.setText(getValueOrEmpty(tbl, selectedRow, 6));
        txtOut.setText(getValueOrEmpty(tbl, selectedRow, 7));
        txtSeat.setText(getValueOrEmpty(tbl, selectedRow, 8));
    } catch (ArrayIndexOutOfBoundsException e) {
        // Handle the case where column index is out of bounds
        JOptionPane.showMessageDialog(this, "Error: Column index is out of bounds.");
        e.printStackTrace();
    } catch (Exception e) {
        // Handle other possible exceptions
        JOptionPane.showMessageDialog(this, "Error: An unexpected error occurred.");
        e.printStackTrace();
    }
} else {
    JOptionPane.showMessageDialog(this, "No row selected.");
}
        
    }//GEN-LAST:event_tblLogMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        
        DefaultTableModel tb = (DefaultTableModel) tblLog.getModel();
        TableRowSorter<DefaultTableModel> tbl = new TableRowSorter<>(tb);
        tblLog.setRowSorter(tbl);
        tbl.setRowFilter(RowFilter.regexFilter(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String msg=lblRole.getText();
          new Barcode(msg).setVisible(true);
            setVisible(false); 
    }//GEN-LAST:event_jButton2ActionPerformed
    private void loadTable(){
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("SELECT * FROM logs");
        
        
         rs=ps.executeQuery();
         while (rs.next()){
             String log = rs.getString("log_id");
             String acc = rs.getString("account_id");
             String seatId = rs.getString("seat_plan_id");
             String sid = rs.getString("student_info_id");
             String studId = rs.getString("studentID");
             String date = rs.getString("date");
             String time_in = rs.getString("time_in");
             String time_out = rs.getString("time_out");
             String seat = rs.getString("seat");
             
             String tbData[] = {log,acc,seatId,sid,studId,date,time_in,time_out,seat};
             DefaultTableModel tbl = (DefaultTableModel) tblLog.getModel();
             
             tbl.addRow(tbData);
        
             
         }
    } catch (SQLException ex) {
        Logger.getLogger(logs.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
       
    
    private String getValueOrEmpty(DefaultTableModel tbl, int row, int column) {
    Object value = tbl.getValueAt(row, column);
    return value != null ? value.toString() : "";
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccReg;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudReg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblLog;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtIn;
    private javax.swing.JTextField txtLog;
    private javax.swing.JTextField txtOut;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtSeatId;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtStud;
    // End of variables declaration//GEN-END:variables
}
