/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.java2d.pipe.BufferedBufImgOps;
import net.sourceforge.jbarcodebean.JBarcodeBean;
import net.sourceforge.jbarcodebean.model.Code128;
import net.sourceforge.jbarcodebean.model.Code39;




/**
 *
 * @author qr_monitor
 */
public class StudentRegister extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps;
ResultSet rs;

private  BufferedImage image = null;
    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
        
        
    }public StudentRegister(String msg){
        initComponents();
        lblRole.setText(msg);
        txtSid.setVisible(false);
        load_stud_info();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStudReg = new javax.swing.JButton();
        btnAccReg = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStudId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        btnLogs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStud = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        txtSid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 760));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1366, 760));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1329, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudReg.setBackground(new java.awt.Color(51, 255, 102));
        btnStudReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnStudReg.setText("Student Register");
        btnStudReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        btnAccReg.setBackground(new java.awt.Color(204, 255, 204));
        btnAccReg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAccReg.setText("Account Register");
        btnAccReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, 30));

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConfirm.setText("Proceed");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Student ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Full Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Course:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Year Level:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Contact Number:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        txtStudId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStudId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStudId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 30));

        txtCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, 30));

        txtYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 280, 30));

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumKeyPressed(evt);
            }
        });
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 280, 30));

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 30));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 60, 20));

        btnLogs.setBackground(new java.awt.Color(204, 255, 204));
        btnLogs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogs.setText("Logs");
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        tblStud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Student ID", "Name", "Course ", "Year Level", "Contact Number"
            }
        ));
        tblStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStud);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 890, 590));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, 30));
        jPanel1.add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 90, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Create Barcode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtStudId.setText("");
        txtName.setText("");
        txtCourse.setText("");
        txtNum.setText("");
        txtYear.setText("");
        txtSid.setText("");
        tblStud.clearSelection();
        txtStudId.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
    
        String stud = txtStudId.getText();
String name = txtName.getText();
String course = txtCourse.getText();
String year = txtYear.getText();
String num = txtNum.getText();
String sid = txtSid.getText();

try {
    // Validate input fields
    if (stud.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Student ID!");
        return;
    } else if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Name!");
        return;
    } else if (course.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Course!");
        return;
    } else if (year.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Year Level!");
        return;
    } else if (num.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Contact Number!");
        return;
    }

    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");

    // Check if student ID exists
    ps = conn.prepareStatement("SELECT studentID FROM student_info WHERE studentID = ?");
    ps.setString(1, stud);
    rs = ps.executeQuery();

    boolean studentExists = rs.next();

    if (studentExists && sid.isEmpty()) {
        // Student ID is already registered, do not insert
        JOptionPane.showMessageDialog(this, "Student ID already registered");
    } else if (studentExists && !sid.isEmpty()) {
        // Update existing record
        ps = conn.prepareStatement("UPDATE student_info SET studentID = ?, name = ?, course = ?, year_level = ?, contact_number = ? WHERE student_info_id = ?");
        ps.setString(1, stud);
        ps.setString(2, name);
        ps.setString(3, course);
        ps.setString(4, year);
        ps.setString(5, num);
        ps.setString(6, sid);

        int rowsUpdated = ps.executeUpdate();
        if (rowsUpdated > 0) {
            DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
            int selectedRow = tblStud.getSelectedRow();
            if (selectedRow != -1) {
                tbl.setValueAt(stud, selectedRow, 1);
                tbl.setValueAt(name, selectedRow, 2);
                tbl.setValueAt(course, selectedRow, 3);
                tbl.setValueAt(year, selectedRow, 4);
                tbl.setValueAt(num, selectedRow, 5);
                JOptionPane.showMessageDialog(null, "Data Updated Successfully");
                txtStudId.setText("");
        txtName.setText("");
        txtCourse.setText("");
        txtYear.setText("");
        txtNum.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to update");
            }
        }
    } else {
        // Insert new record
        ps = conn.prepareStatement("INSERT INTO student_info (studentID, name, course, year_level, contact_number) VALUES (?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
        ps.setString(1, stud);
        ps.setString(2, name);
        ps.setString(3, course);
        ps.setString(4, year);
        ps.setString(5, num);
        ps.executeUpdate();

        ResultSet generatedKeys = ps.getGeneratedKeys();
        int newId = -1;
        if (generatedKeys.next()) {
            newId = generatedKeys.getInt(1);
        }

        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        tbl.addRow(new Object[]{newId, stud, name, course, year, num});

        txtStudId.setText("");
        txtName.setText("");
        txtCourse.setText("");
        txtYear.setText("");
        txtNum.setText("");

        JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
    }
} catch (SQLException ex) {
    Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
} finally {
    // Close resources
    try {
        if (rs != null) rs.close();
        if (ps != null) ps.close();
        if (conn != null) conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
} 
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    private void txtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            txtNum.setEditable(false);
        }else if (Character.isLetter(c)){
            txtNum.setEditable(false);
        }else {
            txtNum.setEditable(true);
        }
    }//GEN-LAST:event_txtNumKeyPressed

    private void btnAccRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccRegActionPerformed
        // TODO add your handling code here:
        if(lblRole.getText().equals("Professor")){
            JOptionPane.showMessageDialog(this, "Access Denied!");
           
        
           
      }else {
          String msg=lblRole.getText();
          new AccRegister(msg).setVisible(true);
            setVisible(false);     
      }
        
    }//GEN-LAST:event_btnAccRegActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        /*Homepage hp = new Homepage();
        hp.show();
        dispose();*/
        String msg=lblRole.getText();
        
        new Homepage(msg).setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnStudRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudRegActionPerformed

    private void txtStudIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudIdActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        String msg=lblRole.getText();
        
        new logs(msg).setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnLogsActionPerformed

    private void tblStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblStud.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        txtSid.setText(tbl.getValueAt(selectedRow, 0).toString());
        txtStudId.setText(tbl.getValueAt(selectedRow, 1).toString());
        txtName.setText(tbl.getValueAt(selectedRow, 2).toString());
        txtCourse.setText(tbl.getValueAt(selectedRow, 3).toString());
        txtYear.setText(tbl.getValueAt(selectedRow, 4).toString());
        txtNum.setText(tbl.getValueAt(selectedRow, 5).toString());
        txtStudId.setEnabled(false);
    }//GEN-LAST:event_tblStudMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtStudId.getText();
        txtStudId.setEnabled(true);
        try {
        // TODO add your handling code here
       
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("DELETE FROM student_info WHERE studentID=?");
        
        ps.setString(1,(id));
        ps.executeUpdate();
        
        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        int SelectedRowIndex = tblStud.getSelectedRow();
        tbl.removeRow(SelectedRowIndex);
            txtStudId.setText("");    
            txtName.setText("");
            txtCourse.setText("");
            txtYear.setText("");
            txtNum.setText("");
            txtSid.setText("");
            JOptionPane.showMessageDialog(null ,"Data Deleted Succesfully!" );
       
        } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String msg=lblRole.getText();
          new Barcode(msg).setVisible(true);
            setVisible(false);   
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public void load_stud_info(){
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("SELECT * FROM student_info");
        rs=ps.executeQuery();
        
         while (rs.next()){
             String sid = rs.getString("student_info_id");
             String studid = rs.getString("studentID");
             String name = rs.getString("name");
             String course = rs.getString("course");
             String year = rs.getString("year_level");
             String num = rs.getString("contact_number");
            
             
             String tbData[] = {sid,studid,name,course,year,num};
             DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
             
             tbl.addRow(tbData);
         
        
             
         } 
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        
    }
         
    
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccReg;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudReg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblStud;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtStudId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
