/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qr_monitor
 */
public class View extends javax.swing.JFrame {
Connection conn;
PreparedStatement ps,ps2;
ResultSet rs,rs2;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
       
        
        
        
    }public View(String msg){
        initComponents();
        lblRole.setText(msg);
        tblAccFalse();
        
         try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("SELECT * FROM student_info");
        ps2=conn.prepareStatement("SELECT * FROM account");
        
        
         rs=ps.executeQuery();
         rs2=ps2.executeQuery();
         while (rs.next()){
             String sid = rs.getString("student_info_id");
             String studid = rs.getString("studentID");
             String name = rs.getString("name");
             String course = rs.getString("course");
             String year = rs.getString("year_level");
             String num = rs.getString("contact_number");
            
             
             String tbData[] = {sid,studid,name,course,year,num};
             DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
             
             tbl.addRow(tbData);
         
        
             
         } while (rs2.next()){
             String aid = rs2.getString("account_id");
             String role = rs2.getString("role");
             String name2 = rs2.getString("name");
             String username = rs2.getString("username");
             String pass = rs2.getString("password");
             String num2 = rs2.getString("contact_number");
             
             String tbData[] = {aid,role,name2,username,pass,num2};
             DefaultTableModel tbl2 = (DefaultTableModel) tblAcc.getModel();
             
             tbl2.addRow(tbData);
        
             
         
       }
         
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        
    }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnStudReg = new javax.swing.JButton();
        btnAccReg = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStud = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtStudId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        pnlAcc = new javax.swing.JPanel();
        btnDelete2 = new javax.swing.JButton();
        txtName2 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtAccId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcc = new javax.swing.JTable();
        txtRole = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate2 = new javax.swing.JButton();
        txtPass = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 768));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudReg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnStudReg.setText("Student Register");
        btnStudReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        btnAccReg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAccReg.setText("Account Register");
        btnAccReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("View Information");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, -1, -1));

        tblStud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "Student ID", "Name", "Course", "Year Level", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblStud);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 620, 300));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 210, -1, -1));

        jLabel6.setText("Student ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jLabel7.setText("Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, -1, -1));

        jLabel8.setText("Course:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));

        jLabel9.setText("Year Level:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

        jLabel10.setText("Contact Number:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        txtStudId.setEnabled(false);
        jPanel1.add(txtStudId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 140, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 140, -1));
        jPanel1.add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 140, -1));
        jPanel1.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 140, -1));

        txtNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumMouseClicked(evt);
            }
        });
        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumKeyPressed(evt);
            }
        });
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 140, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, -1, -1));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 70, 20));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, -1, -1));

        btnLogs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLogs.setText("Logs");
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, -1));

        jLabel1.setText("SID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        txtSid.setEnabled(false);
        jPanel1.add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 140, -1));

        pnlAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete2.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });
        pnlAcc.add(btnDelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        txtName2.setEnabled(false);
        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });
        pnlAcc.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 140, -1));

        lbl4.setText("Password:");
        pnlAcc.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        lbl2.setText("Name:");
        pnlAcc.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        lbl3.setText("Username:");
        pnlAcc.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));
        pnlAcc.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 140, -1));

        txtAccId.setEnabled(false);
        txtAccId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccIdActionPerformed(evt);
            }
        });
        pnlAcc.add(txtAccId, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 140, -1));

        tblAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acc ID", "Role", "Name", "Username", "Password", "Contact Number"
            }
        ));
        tblAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAcc);

        pnlAcc.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 620, 300));

        txtRole.setEnabled(false);
        txtRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleActionPerformed(evt);
            }
        });
        pnlAcc.add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 140, 30));

        lbl5.setText("Contact Number:");
        pnlAcc.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        lbl1.setText("Role:");
        pnlAcc.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jLabel2.setText("Account ID:");
        pnlAcc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        btnUpdate2.setText("Update");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        pnlAcc.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));
        pnlAcc.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 140, -1));

        txtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNum2KeyPressed(evt);
            }
        });
        pnlAcc.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 140, -1));

        jPanel1.add(pnlAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 1000, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        /*Homepage hp = new Homepage();
        hp.show();
        dispose();*/
        String msg=lblRole.getText();
        
        new Homepage(msg).setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnStudRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudRegActionPerformed
        // TODO add your handling code here:
        /*StudentRegister sr = new StudentRegister();
        sr.show();
        dispose();*/
        String msg=lblRole.getText();
        
        new StudentRegister(msg).setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnStudRegActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAccRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccRegActionPerformed
        // TODO add your handling code here:
       if(lblRole.getText().equals("Professor")){
            JOptionPane.showMessageDialog(this, "Access Denied!");
           
        
           
      }else{
          String msg=lblRole.getText();
          new AccRegister(msg).setVisible(true);
            setVisible(false);     
      }
        
        
    }//GEN-LAST:event_btnAccRegActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblStud.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        txtSid.setText(tbl.getValueAt(selectedRow, 0).toString());
        txtStudId.setText(tbl.getValueAt(selectedRow, 1).toString());
        txtName.setText(tbl.getValueAt(selectedRow, 2).toString());
        txtCourse.setText(tbl.getValueAt(selectedRow, 3).toString());
        txtYear.setText(tbl.getValueAt(selectedRow, 4).toString());
        txtNum.setText(tbl.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_tblStudMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        try {
    // Establish database connection
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
    
    // Prepare the SQL statement
    String sql = "UPDATE student_info SET name = ?, course = ?, year_level = ?, contact_number = ? WHERE studentID = ?";
    ps = conn.prepareStatement(sql);
    
    // Set parameters for the SQL query
    ps.setString(1, txtName.getText());
    ps.setString(2, txtCourse.getText());
    ps.setString(3, txtYear.getText());
    ps.setString(4, txtNum.getText());
    ps.setString(5, txtStudId.getText());
    
    // Execute the update query
    int rowsUpdated = ps.executeUpdate();
    DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
    int selectedRow = tblStud.getSelectedRow();
    
    if (rowsUpdated > 0) {
        // Update JTable
        tbl.setValueAt(txtStudId.getText(), selectedRow, 0); // Assuming studentID is in the first column
        tbl.setValueAt(txtName.getText(), selectedRow, 1);
        tbl.setValueAt(txtCourse.getText(), selectedRow, 2);
        tbl.setValueAt(txtYear.getText(), selectedRow, 3);
        tbl.setValueAt(txtNum.getText(), selectedRow, 4);
        
        JOptionPane.showMessageDialog(null, "Data Updated Successfully");
        
        // Clear text fields
        txtStudId.setText("");
        txtName.setText("");
        txtCourse.setText("");
        txtYear.setText("");
        txtNum.setText("");
    } else {
        JOptionPane.showMessageDialog(null, "Update Failed: No Rows Affected");
    }
    
} catch (SQLException ex) {
    // Improved exception handling
    JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
    Logger.getLogger(View.class.getName()).log(Level.SEVERE, "SQLException occurred", ex);
} finally {
    // Clean up resources
    try {
        if (ps != null) ps.close();
        if (conn != null) conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, "Error closing resources", ex);
    }
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtNumMouseClicked

    private void txtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            txtNum.setEditable(false);
        }else if (Character.isLetter(c)){
            txtNum.setEditable(false);
        }else {
            txtNum.setEditable(true);
        }
    }//GEN-LAST:event_txtNumKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtStudId.getText();
        try {
        // TODO add your handling code here
       
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
        ps=conn.prepareStatement("DELETE FROM student_info WHERE studentID=?");
        
        ps.setString(1,(id));
        ps.executeUpdate();
        
        DefaultTableModel tbl = (DefaultTableModel) tblStud.getModel();
        int SelectedRowIndex = tblStud.getSelectedRow();
        tbl.removeRow(SelectedRowIndex);
            txtStudId.setText("");    
            txtName.setText("");
            txtCourse.setText("");
            txtYear.setText("");
            txtNum.setText("");
            JOptionPane.showMessageDialog(null ,"Data Deleted Succesfully!" );
       
        } catch (SQLException ex) {
        Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        String msg=lblRole.getText();
        
        new logs(msg).setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
        try {
            // Establish database connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");

            // Prepare the SQL statement
            String sql = "UPDATE account SET role = ?, username = ?, password = ?, contact_number = ? WHERE name = ?";
            ps = conn.prepareStatement(sql);

            // Set parameters for the SQL query
            ps.setString(1, txtRole.getText());
            ps.setString(2, txtUsername.getText());
            ps.setString(3, txtPass.getText());
            ps.setString(4, txtNum2.getText());
            ps.setString(5, txtName2.getText());

            // Execute the update query
            int rowsUpdated = ps.executeUpdate();
            DefaultTableModel tbl = (DefaultTableModel) tblAcc.getModel();
            int selectedRow = tblAcc.getSelectedRow();

            if (rowsUpdated > 0) {
                // Update JTable
                tbl.setValueAt(txtRole.getText(), selectedRow, 0); // Assuming studentID is in the first column
                tbl.setValueAt(txtName2.getText(), selectedRow, 1);
                tbl.setValueAt(txtUsername.getText(), selectedRow, 2);
                tbl.setValueAt(txtPass.getText(), selectedRow, 3);
                tbl.setValueAt(txtNum2.getText(), selectedRow, 4);

                JOptionPane.showMessageDialog(null, "Data Updated Successfully");

                // Clear text fields
                txtRole.setText("");
                txtName2.setText("");
                txtUsername.setText("");
                txtPass.setText("");
                txtNum2.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Update Failed: No Rows Affected");
            }

        } catch (SQLException ex) {
            // Improved exception handling
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, "SQLException occurred", ex);
        } finally {
            // Clean up resources
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, "Error closing resources", ex);
            }
        }

    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
        // TODO add your handling code here:
        String name = txtName2.getText();
        try {
            // TODO add your handling code here

            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crudv2_db", "root", "");
            ps=conn.prepareStatement("DELETE FROM account WHERE name=?");

            ps.setString(1,(name));
            ps.executeUpdate();

            DefaultTableModel tbl = (DefaultTableModel) tblAcc.getModel();
            int SelectedRowIndex = tblAcc.getSelectedRow();
            tbl.removeRow(SelectedRowIndex);
            txtRole.setText("");
            txtName2.setText("");
            txtUsername.setText("");
            txtPass.setText("");
            txtNum2.setText("");
            JOptionPane.showMessageDialog(null ,"Data Deleted Succesfully!" );

        } catch (SQLException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void txtNum2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            txtNum2.setEditable(false);
        }else if (Character.isLetter(c)){
            txtNum2.setEditable(false);
        }else {
            txtNum2.setEditable(true);
        }
    }//GEN-LAST:event_txtNum2KeyPressed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtName2ActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRoleActionPerformed

    private void txtAccIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccIdActionPerformed

    private void tblAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblAcc.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblAcc.getModel();
        txtAccId.setText(tbl.getValueAt(selectedRow, 0).toString());
        txtRole.setText(tbl.getValueAt(selectedRow, 1).toString());
        txtName2.setText(tbl.getValueAt(selectedRow, 2).toString());
        txtUsername.setText(tbl.getValueAt(selectedRow, 3).toString());
        txtPass.setText(tbl.getValueAt(selectedRow, 4).toString());
        txtNum2.setText(tbl.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_tblAccMouseClicked

    private void tblAccFalse(){
        if(lblRole.getText().equals("Professor")){
         pnlAcc.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccReg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudReg;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel pnlAcc;
    private javax.swing.JTable tblAcc;
    private javax.swing.JTable tblStud;
    private javax.swing.JTextField txtAccId;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtStudId;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
